CREATE SCHEMA `noteswebapp` ;
--
CREATE TABLE user_table (
  UserID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Username VARCHAR(50) NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL,
  CreatedAT TIMESTAMP NOT NULL,
  TemplateID INTEGER NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE Note (
  NoteID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Title VARCHAR(255),
  TextContent TEXT,
  Pinned BOOLEAN NOT NULL,
  Hidden BOOLEAN NOT NULL,
  Cosmetics TEXT,
  ViewOnly BOOLEAN NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UserID INTEGER NOT NULL,
  Deleted BOOLEAN,
  timeLeftBeforeDeletion TIMESTAMP,
  LabelID INTEGER,
  colorID INTEGER
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE label (
  LabelName VARCHAR(50) NOT NULL,
  UserID INTEGER NOT NULL UNIQUE,
  labelID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE notecolor (
  UserID INTEGER NOT NULL,
  colorHEX VARCHAR(7) NOT NULL,
  colorID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE uitemplates (
  TemplateID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  Name VARCHAR(25) NOT NULL,
  TemplateDetails TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

ALTER TABLE user_table ADD CONSTRAINT fk_user_table_TemplateID FOREIGN KEY (TemplateID) REFERENCES uitemplates(TemplateID) ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE Note ADD CONSTRAINT fk_Note_UserID FOREIGN KEY (UserID) REFERENCES user_table(UserID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Note ADD CONSTRAINT fk_Note_LabelID FOREIGN KEY (LabelID) REFERENCES label(labelID) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE Note ADD CONSTRAINT fk_Note_colorID FOREIGN KEY (colorID) REFERENCES notecolor(colorID) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE label ADD CONSTRAINT fk_label_UserID FOREIGN KEY (UserID) REFERENCES user_table(UserID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE notecolor ADD CONSTRAINT fk_notecolor_UserID FOREIGN KEY (UserID) REFERENCES user_table(UserID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX idx_User_Table_ ON user_table (UserID);
CREATE INDEX idx_user_table_TemplateID ON user_table (TemplateID);

CREATE INDEX idx_Note_UserID ON Note (UserID);
CREATE INDEX idx_Note_LabelName ON Note (LabelID);

CREATE INDEX idx_Label_UserID ON label (UserID);

CREATE INDEX idx_notecolor_UserID ON notecolor (UserID);

CREATE INDEX idx_UITemplates_ ON uitemplates (TemplateID);
